export const NEW_WALLET = 'NEW_WALLET';
export const RECOVER_WALLET_MNEMONIC = 'RECOVER_WALLET_MNEMONIC';
export const RECOVER_WALLET_PRIVATEKEY = 'RECOVER_WALLET_PRIVATEKEY';
export const CONNECTED_WALLET = 'CONNECTED_WALLET';

export const MAIN_NET = 'MAINNET';
export const TEST_NET = 'TESTNET';
