export const HANDLE_CHAIN_NETWORK = 'HANDLE_CHAIN_NETWORK';
export const HANDLE_WALLET_DATA = 'HANDLE_WALLET_DATA';
export const HANDLE_WALLET = 'HANDLE_WALLET';
export const HANDLE_WALLET_BALANCE = 'HANDLE_WALLET_BALANCE';
export const HANDLE_WALLET_PRIVATEKEY = 'HANDLE_WALLET_PRIVATEKEY';
export const HANDLE_WALLET_ADDRESS = 'HANDLE_WALLET_ADDRESS';

export const HANDLE_LOADING_PROGRESS = 'HANDLE_LOADING_PROGRESS';
export const HANDLE_MODAL_RESET = 'HANDLE_MODAL_RESET';
export const HANDLE_MODAL_DATA = 'HANDLE_MODAL_DATA';
export const HANDLE_MODAL_WALLET_CONNECT = 'HANDLE_MODAL_WALLET_CONNECT';
export const HANDLE_MODAL_WALLET = 'HANDLE_MODAL_WALLET';
export const HANDLE_MODAL_QUEUETX = 'HANDLE_MODAL_QUEUETX';
export const HANDLE_MODAL_EDIT_HASHKEY = 'HANDLE_MODAL_EDIT_HASHKEY';

export const FILE = 'FILE';
export const FILE_HASH = 'FILE_HASH';
export const ORIGINAL_CONTRACT = 'ORIGINAL_CONTRACT';
export const META_JSON = 'META_JSON';

export const DEMO = "DEMO";
export const VERIFY_STEP = 'VERIFY_STEP';
export const SHOW_VERIFICATION = 'SHOW_VERIFICATION';

export const NEW_WALLET = 'NEW_WALLET';
export const RECOVER_WALLET_MNEMONIC = 'RECOVER_WALLET_MNEMONIC';
export const RECOVER_WALLET_PRIVATEKEY = 'RECOVER_WALLET_PRIVATEKEY';
export const CONNECTED_WALLET = 'CONNECTED_WALLET';

export const MAIN_NET = "MAINNET";
export const TEST_NET = "TESTNET";