export const HANDLE_WALLET_DATA = 'HANDLE_WALLET_DATA';
export const HANDLE_WALLET_BALANCE = 'HANDLE_WALLET_BALANCE';
export const HANDLE_WALLET_PRIVATEKEY = 'HANDLE_WALLET_PRIVATEKEY';
export const HANDLE_WALLET_ADDRESS = 'HANDLE_WALLET_ADDRESS';

export const HANDLE_MODAL_RESET = 'HANDLE_MODAL_RESET';
export const HANDLE_MODAL_DATA = 'HANDLE_MODAL_DATA';
export const HANDLE_MODAL_WALLET = 'HANDLE_MODAL_WALLET';
export const HANDLE_MODAL_QUEUETX = 'HANDLE_MODAL_QUEUETX';

export const FILE = 'FILE';
export const ORIGINAL_CONTRACT = 'ORIGINAL_CONTRACT';
export const META_JSON = 'META_JSON';

export const DEMO = "DEMO";
export const VERIFY_STEP = 'VERIFY_STEP';
export const SHOW_VERIFICATION = 'SHOW_VERIFICATION';